name: bluejay
description: A UI Kit for Flutter.
version: 1.0.0
homepage:

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.jacobbrasil.bluejay
        pluginClass: BluejayPlugin
      ios:
        pluginClass: BluejayPlugin
      linux:
        pluginClass: BluejayPlugin
      macos:
        pluginClass: BluejayPlugin
      windows:
        pluginClass: BluejayPluginCApi
      web:
        pluginClass: BluejayWeb
        fileName: bluejay_web.dart

  fonts:
    - family: UberMove
      fonts:
        - asset: assets/fonts/UberMove-Light.ttf
          weight: 300
        - asset: assets/fonts/UberMove-Regular.ttf
        - asset: assets/fonts/UberMove-Medium.ttf
          weight: 500
        - asset: assets/fonts/UberMove-Bold.ttf
          weight: 700
    - family: UberMoveMono
      fonts:
        - asset: assets/fonts/UberMoveMono-Regular.ttf
        - asset: assets/fonts/UberMoveMono-Medium.ttf
          weight: 500
    - family: UberMoveText
      fonts:
        - asset: assets/fonts/UberMoveText-Light.otf
          weight: 300
        - asset: assets/fonts/UberMoveText-Regular.otf
        - asset: assets/fonts/UberMoveText-Medium.otf
          weight: 500
        - asset: assets/fonts/UberMoveText-Bold.otf
          weight: 700
